/* ============================================================================
   Hero WebGL — "The Sovereign Core" (matte / editorial)
   Loads the procedurally-generated Blender asset (public/models/core.glb) — a
   faceted graphite monolith — and lights it with soft image-based light + a
   warm key and a sage rim. NO bloom, NO neon: a dark sculptural object that
   picks up light without glowing, sitting behind the type like a gallery piece.
   The form is generated by blender/gen_core.py (rule-based noise displacement).
   ========================================================================== */
import * as THREE from "three";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader.js";
import { RoomEnvironment } from "three/examples/jsm/environments/RoomEnvironment.js";

export function initHero(canvas: HTMLCanvasElement, onReady?: () => void) {
  const reduced = matchMedia("(prefers-reduced-motion: reduce)").matches;
  const wide = () => innerWidth > 900;

  const renderer = new THREE.WebGLRenderer({
    canvas, antialias: true, alpha: true, powerPreference: "high-performance",
  });
  renderer.setPixelRatio(Math.min(devicePixelRatio, 2));
  renderer.setSize(innerWidth, innerHeight);
  renderer.outputColorSpace = THREE.SRGBColorSpace;
  renderer.toneMapping = THREE.ACESFilmicToneMapping;
  renderer.toneMappingExposure = 0.82;            // keep it restrained — never glowing

  const scene = new THREE.Scene();
  const camera = new THREE.PerspectiveCamera(34, innerWidth / innerHeight, 0.1, 100);
  camera.position.set(0, 0, 6.6);

  // ── soft image-based light: gives the metal subtle, premium reflections ──
  const pmrem = new THREE.PMREMGenerator(renderer);
  const envRT = pmrem.fromScene(new RoomEnvironment(), 0.04);
  scene.environment = envRT.texture;
  (scene as any).environmentIntensity = 0.34;     // dialled low so it reads dark

  // ── direct lights for rim/form definition ──
  const key = new THREE.DirectionalLight(0xffe8cc, 2.3);   // warm key, upper-right
  key.position.set(4, 5, 3);
  const rim = new THREE.DirectionalLight(0xb7c0b3, 1.5);   // sage rim, behind-left
  rim.position.set(-5, 2, -4);
  const fill = new THREE.DirectionalLight(0x8a93a0, 0.5);  // cool fill, low
  fill.position.set(-2, -3, 2);
  scene.add(key, rim, fill);

  // ── the procedural core ──
  const group = new THREE.Group();
  scene.add(group);
  let baseScale = 1;

  let targetScale = 1;
  const place = () => {
    const w = wide();
    group.position.x = w ? 1.85 : 0;
    group.position.y = w ? 0.55 : 1.15;
    targetScale = baseScale * (w ? 1 : 0.78);
  };

  new GLTFLoader().load(
    "/models/core.glb",
    (gltf) => {
      const core = gltf.scene;
      // fit: normalise the imported size to a stable on-screen radius
      const box = new THREE.Box3().setFromObject(core);
      const r = box.getBoundingSphere(new THREE.Sphere()).radius || 1;
      baseScale = 1.7 / r;
      core.traverse((o) => {
        const m = (o as THREE.Mesh).material as THREE.MeshStandardMaterial | undefined;
        if (m) { m.envMapIntensity = 0.34; }
      });
      group.add(core);
      place();
      renderer.render(scene, camera);   // first paint as soon as the asset is in
      onReady?.();
    },
    undefined,
    () => onReady?.(),   // never block the hero if the asset 404s
  );

  // ── gentle pointer parallax (rotates the object, keeps composition stable) ──
  const target = new THREE.Vector2(), cur = new THREE.Vector2();
  addEventListener("mousemove", (e) => {
    target.set((e.clientX / innerWidth - 0.5) * 2, -(e.clientY / innerHeight - 0.5) * 2);
  });

  let paused = false;
  document.addEventListener("visibilitychange", () => (paused = document.hidden));
  const dimmed = () => canvas.classList.contains("is-dim");
  const clock = new THREE.Clock();
  const INTRO = 1.6;                 // seconds for the core to settle into frame
  let capFrozen = false;

  const applyMotion = (t: number) => {
    const k = Math.min(1, t / INTRO);
    const e = 1 - Math.pow(1 - k, 3);                            // easeOutCubic
    cur.lerp(target, 0.045);
    group.rotation.y = t * 0.11 + cur.x * 0.32 + (1 - e) * 0.9;  // extra spin that settles
    group.rotation.x = Math.sin(t * 0.4) * 0.06 + cur.y * 0.2;
    group.position.y += ((wide() ? 0.55 : 1.15) + Math.sin(t * 0.5) * 0.07 - group.position.y) * 0.1;
    group.scale.setScalar(targetScale * (0.8 + 0.2 * e));        // scale-in entrance
  };

  function tick() {
    const t = clock.getElapsedTime();
    // capture mode: play the intro, render one settled frame, then STOP. A live
    // rAF loop starves headless screenshots on software GL (causes timeouts).
    if ((window as any).__CAP) {
      if (t < INTRO + 0.25) { applyMotion(t); renderer.render(scene, camera); requestAnimationFrame(tick); }
      else if (!capFrozen) { capFrozen = true; applyMotion(INTRO); renderer.render(scene, camera); }
      return;
    }
    requestAnimationFrame(tick);
    if (paused || dimmed()) return;            // skip render when tab hidden or scrolled past
    applyMotion(t);
    renderer.render(scene, camera);
  }
  tick();
  if (reduced) { paused = true; group.scale.setScalar(targetScale); renderer.render(scene, camera); }

  addEventListener("resize", () => {
    camera.aspect = innerWidth / innerHeight;
    camera.updateProjectionMatrix();
    renderer.setSize(innerWidth, innerHeight);
    place();
  });
}
