apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  # Single replica in dev
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: tsm-detector
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: tsm-control-plane

  # Debug logging in dev
  - patch: |-
      - op: replace
        path: /data/TSM_LOG_LEVEL
        value: "debug"
      - op: replace
        path: /data/TSM_CP_LOG_LEVEL
        value: "debug"
    target:
      kind: ConfigMap
      name: tsm-config

images:
  - name: tsm/dataplane
    newTag: dev
  - name: tsm/detector
    newTag: dev
  - name: tsm/control-plane
    newTag: dev

commonLabels:
  environment: development
