{{- if or .Values.secrets.openaiApiKey .Values.secrets.anthropicApiKey .Values.secrets.webhookUrl -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    {{- include "tsm.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.openaiApiKey }}
  OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey | quote }}
  {{- end }}
  {{- if .Values.secrets.anthropicApiKey }}
  ANTHROPIC_API_KEY: {{ .Values.secrets.anthropicApiKey | quote }}
  {{- end }}
  {{- if .Values.secrets.webhookUrl }}
  TSM_WEBHOOK_URL: {{ .Values.secrets.webhookUrl | quote }}
  {{- end }}
{{- end }}
